Fit: added implementation of is object empty validator
veritem/valdie pull request #15
Opened 2021-06-02 11:29 UTC by ntwari-egide

2021-06-02 11:39 UTC, makuzaverite requested changes
Add unit tests for this

2021-06-02 16:39 UTC, makuzaverite requested changes
Add unit tests plz we use jest currently

2021-06-02 16:39 UTC, makuzaverite commented on src/areObjectsFromSameType.ts
> +      return false
I can't find any where you are handling errors in this function

2021-06-09 11:15 UTC, veritem commented
@ntwari-egide  we might close this

2021-12-02 22:04 UTC, closed without merging